# Conexión a PostgreSQL
url=jdbc:postgresql://localhost:5432/taller_db
username=postgres
password=postgres

# Archivo maestro de cambios
changeLogFile=src/main/resources/db/changelog/master.xml

# Driver de PostgreSQL
driver=org.postgresql.Driver